-- Auto-generated by db-change-agent
-- change_event_id=15 table=public.orders op=DDL
-- accepted_at=2026-08-25T14:58:49.485639+00:00

-- Diff:
-- {"sql_text": "ALTER TABLE orders ALTER COLUMN total_amount TYPE NUMERIC(12, 2);", "command_tag": "ALTER TABLE", "object_type": "table"}

-- Reviewed impact:
--   orders-service::place_order (orders-service/db.py:17)
--   orders-service::get_orders_for_user (orders-service/db.py:40)
--   refunds-service::request_refund (refunds-service/db.py:17)