-- Auto-generated by db-change-agent
-- change_event_id=16 table=public.refunds op=DDL
-- accepted_at=2026-08-25T15:00:56.361325+00:00

-- Diff:
-- {"sql_text": "ALTER TABLE refunds ALTER COLUMN reason SET NOT NULL;", "command_tag": "ALTER TABLE", "object_type": "table"}

-- Reviewed impact:
--   refunds-service::request_refund (refunds-service/db.py:22)
--   refunds-service::get_refunds_for_order (refunds-service/db.py:49)